vich_uploader:
    db_driver: orm

    mappings: 
        thumbnail:
           uri_prefix: /pics/
           upload_destination: '%kernel.project_dir%/public/uploads/pics'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer